# Site settings
title: Hey, Soy Andrea.
description: Este es mi Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. https://tu-usuario.github.io/tu-repo

# User settings
username: Andrea Pardo Gispert
user_job_title: Desarrolladora Backend Junior | Python, Flask, SQL | Experiencia en Ingeniería y Gestión de Proyectos # Python Developer | AI & ML Researcher | Data Science Enthusiast -  Front-end & Back-end Developer | AI & ML | Data Analysis - Python & Web Developer | AI & ML Enthusiast | Project Mlist | Data Scientistanager - Python Developer | AI & ML Specia
email: andreapardogis [at] gmail.com
linkedin_username: andreapardogis
github_username:  andreapardogis

exclude: ['package.json', 'src' , 'node_modules']
